apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PCC52D03280B7034C
    isDefault: true
    access: proxy
    url: postgres:5432
    user: pom_user
    database: pom_analytics
    editable: true
    jsonData:
      database: pom_analytics
      sslmode: "disable"
      postgresVersion: 1500
    secureJsonData:
      password: "pom_password"
